// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package enum

import (
	"database/sql/driver"
	"errors"
	"fmt"
)

const (
	// ChampionshipTalcCup is a Championship of type TalcCup.
	ChampionshipTalcCup Championship = iota
	// ChampionshipHaliteCup is a Championship of type HaliteCup.
	ChampionshipHaliteCup
	// ChampionshipFluoriteCup is a Championship of type FluoriteCup.
	ChampionshipFluoriteCup
	// ChampionshipQuartzChampionship is a Championship of type QuartzChampionship.
	ChampionshipQuartzChampionship
	// ChampionshipPyriteChamionship is a Championship of type PyriteChamionship.
	ChampionshipPyriteChamionship
	// ChampionshipGarnetChampionship is a Championship of type GarnetChampionship.
	ChampionshipGarnetChampionship
	// ChampionshipCorundumMasters is a Championship of type CorundumMasters.
	ChampionshipCorundumMasters
	// ChampionshipDiamondApex is a Championship of type DiamondApex.
	ChampionshipDiamondApex
	// ChampionshipBismuthGrandChampionship is a Championship of type BismuthGrandChampionship.
	ChampionshipBismuthGrandChampionship
)

var ErrInvalidChampionship = errors.New("not a valid Championship")

const _ChampionshipName = "talcCuphaliteCupfluoriteCupquartzChampionshippyriteChamionshipgarnetChampionshipcorundumMastersdiamondApexbismuthGrandChampionship"

var _ChampionshipMap = map[Championship]string{
	ChampionshipTalcCup:                  _ChampionshipName[0:7],
	ChampionshipHaliteCup:                _ChampionshipName[7:16],
	ChampionshipFluoriteCup:              _ChampionshipName[16:27],
	ChampionshipQuartzChampionship:       _ChampionshipName[27:45],
	ChampionshipPyriteChamionship:        _ChampionshipName[45:62],
	ChampionshipGarnetChampionship:       _ChampionshipName[62:80],
	ChampionshipCorundumMasters:          _ChampionshipName[80:95],
	ChampionshipDiamondApex:              _ChampionshipName[95:106],
	ChampionshipBismuthGrandChampionship: _ChampionshipName[106:130],
}

// String implements the Stringer interface.
func (x Championship) String() string {
	if str, ok := _ChampionshipMap[x]; ok {
		return str
	}
	return fmt.Sprintf("Championship(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Championship) IsValid() bool {
	_, ok := _ChampionshipMap[x]
	return ok
}

var _ChampionshipValue = map[string]Championship{
	_ChampionshipName[0:7]:     ChampionshipTalcCup,
	_ChampionshipName[7:16]:    ChampionshipHaliteCup,
	_ChampionshipName[16:27]:   ChampionshipFluoriteCup,
	_ChampionshipName[27:45]:   ChampionshipQuartzChampionship,
	_ChampionshipName[45:62]:   ChampionshipPyriteChamionship,
	_ChampionshipName[62:80]:   ChampionshipGarnetChampionship,
	_ChampionshipName[80:95]:   ChampionshipCorundumMasters,
	_ChampionshipName[95:106]:  ChampionshipDiamondApex,
	_ChampionshipName[106:130]: ChampionshipBismuthGrandChampionship,
}

// ParseChampionship attempts to convert a string to a Championship.
func ParseChampionship(name string) (Championship, error) {
	if x, ok := _ChampionshipValue[name]; ok {
		return x, nil
	}
	return Championship(0), fmt.Errorf("%s is %w", name, ErrInvalidChampionship)
}

// MarshalText implements the text marshaller method.
func (x Championship) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Championship) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseChampionship(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *Championship) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

var errChampionshipNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *Championship) Scan(value interface{}) (err error) {
	if value == nil {
		*x = Championship(0)
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case int64:
		*x = Championship(v)
	case string:
		*x, err = ParseChampionship(v)
	case []byte:
		*x, err = ParseChampionship(string(v))
	case Championship:
		*x = v
	case int:
		*x = Championship(v)
	case *Championship:
		if v == nil {
			return errChampionshipNilPtr
		}
		*x = *v
	case uint:
		*x = Championship(v)
	case uint64:
		*x = Championship(v)
	case *int:
		if v == nil {
			return errChampionshipNilPtr
		}
		*x = Championship(*v)
	case *int64:
		if v == nil {
			return errChampionshipNilPtr
		}
		*x = Championship(*v)
	case float64: // json marshals everything as a float64 if it's a number
		*x = Championship(v)
	case *float64: // json marshals everything as a float64 if it's a number
		if v == nil {
			return errChampionshipNilPtr
		}
		*x = Championship(*v)
	case *uint:
		if v == nil {
			return errChampionshipNilPtr
		}
		*x = Championship(*v)
	case *uint64:
		if v == nil {
			return errChampionshipNilPtr
		}
		*x = Championship(*v)
	case *string:
		if v == nil {
			return errChampionshipNilPtr
		}
		*x, err = ParseChampionship(*v)
	}

	return
}

// Value implements the driver Valuer interface.
func (x Championship) Value() (driver.Value, error) {
	return x.String(), nil
}
