openapi: 3.1.0
info:
  title: Souark API
  description: .
  version: 0.0.3

servers:
  - url: http://localhost:7777
    description: Development server

tags:
  - name: version
    description: API version
  - name: player
    description: Player collection
  - name: team
    description: Team collection
  - name: game
    description: Game collection

paths:
  /api/version:
    $ref: "./version/version.yml"
  /api/player:
    $ref: "./player/player.yml"
  /api/player/{id}:
    $ref: "./player/playerId.yml"
  /api/team:
    $ref: "./team/team.yml"
  /api/team/new:
    $ref: "./team/teamNew.yml"
  /api/team/{id}:
    $ref: "./team/teamId.yml"
  /api/game:
    $ref: "./game/game.yml"
  /api/game/new:
    $ref: "./game/gameNew.yml"
  /api/game/{id}:
    $ref: "./game/gameId.yml"
