// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package enum

import (
	"errors"
	"fmt"
)

const (
	// DivisionBeginnerOne is a Division of type BeginnerOne.
	DivisionBeginnerOne Division = iota
	// DivisionBeginnerTwo is a Division of type BeginnerTwo.
	DivisionBeginnerTwo
	// DivisionBeginnerThree is a Division of type BeginnerThree.
	DivisionBeginnerThree
	// DivisionAdvancedOne is a Division of type AdvancedOne.
	DivisionAdvancedOne
	// DivisionAdvancedTwo is a Division of type AdvancedTwo.
	DivisionAdvancedTwo
	// DivisionAdvancedThree is a Division of type AdvancedThree.
	DivisionAdvancedThree
	// DivisionProfessionalOne is a Division of type ProfessionalOne.
	DivisionProfessionalOne
	// DivisionProfessionalTwo is a Division of type ProfessionalTwo.
	DivisionProfessionalTwo
	// DivisionProfessionalThree is a Division of type ProfessionalThree.
	DivisionProfessionalThree
)

var ErrInvalidDivision = errors.New("not a valid Division")

const _DivisionName = "beginnerOnebeginnerTwobeginnerThreeadvancedOneadvancedTwoadvancedThreeprofessionalOneprofessionalTwoprofessionalThree"

var _DivisionMap = map[Division]string{
	DivisionBeginnerOne:       _DivisionName[0:11],
	DivisionBeginnerTwo:       _DivisionName[11:22],
	DivisionBeginnerThree:     _DivisionName[22:35],
	DivisionAdvancedOne:       _DivisionName[35:46],
	DivisionAdvancedTwo:       _DivisionName[46:57],
	DivisionAdvancedThree:     _DivisionName[57:70],
	DivisionProfessionalOne:   _DivisionName[70:85],
	DivisionProfessionalTwo:   _DivisionName[85:100],
	DivisionProfessionalThree: _DivisionName[100:117],
}

// String implements the Stringer interface.
func (x Division) String() string {
	if str, ok := _DivisionMap[x]; ok {
		return str
	}
	return fmt.Sprintf("Division(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Division) IsValid() bool {
	_, ok := _DivisionMap[x]
	return ok
}

var _DivisionValue = map[string]Division{
	_DivisionName[0:11]:    DivisionBeginnerOne,
	_DivisionName[11:22]:   DivisionBeginnerTwo,
	_DivisionName[22:35]:   DivisionBeginnerThree,
	_DivisionName[35:46]:   DivisionAdvancedOne,
	_DivisionName[46:57]:   DivisionAdvancedTwo,
	_DivisionName[57:70]:   DivisionAdvancedThree,
	_DivisionName[70:85]:   DivisionProfessionalOne,
	_DivisionName[85:100]:  DivisionProfessionalTwo,
	_DivisionName[100:117]: DivisionProfessionalThree,
}

// ParseDivision attempts to convert a string to a Division.
func ParseDivision(name string) (Division, error) {
	if x, ok := _DivisionValue[name]; ok {
		return x, nil
	}
	return Division(0), fmt.Errorf("%s is %w", name, ErrInvalidDivision)
}
