// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package enum

import (
	"database/sql/driver"
	"errors"
	"fmt"
)

const (
	// DivisionTalc is a Division of type Talc.
	DivisionTalc Division = iota
	// DivisionHalite is a Division of type Halite.
	DivisionHalite
	// DivisionFluorite is a Division of type Fluorite.
	DivisionFluorite
	// DivisionQuartz is a Division of type Quartz.
	DivisionQuartz
	// DivisionPyrite is a Division of type Pyrite.
	DivisionPyrite
	// DivisionGarnet is a Division of type Garnet.
	DivisionGarnet
	// DivisionCorundum is a Division of type Corundum.
	DivisionCorundum
	// DivisionDiamond is a Division of type Diamond.
	DivisionDiamond
	// DivisionBismuth is a Division of type Bismuth.
	DivisionBismuth
)

var ErrInvalidDivision = errors.New("not a valid Division")

const _DivisionName = "talchalitefluoritequartzpyritegarnetcorundumdiamondbismuth"

var _DivisionMap = map[Division]string{
	DivisionTalc:     _DivisionName[0:4],
	DivisionHalite:   _DivisionName[4:10],
	DivisionFluorite: _DivisionName[10:18],
	DivisionQuartz:   _DivisionName[18:24],
	DivisionPyrite:   _DivisionName[24:30],
	DivisionGarnet:   _DivisionName[30:36],
	DivisionCorundum: _DivisionName[36:44],
	DivisionDiamond:  _DivisionName[44:51],
	DivisionBismuth:  _DivisionName[51:58],
}

// String implements the Stringer interface.
func (x Division) String() string {
	if str, ok := _DivisionMap[x]; ok {
		return str
	}
	return fmt.Sprintf("Division(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Division) IsValid() bool {
	_, ok := _DivisionMap[x]
	return ok
}

var _DivisionValue = map[string]Division{
	_DivisionName[0:4]:   DivisionTalc,
	_DivisionName[4:10]:  DivisionHalite,
	_DivisionName[10:18]: DivisionFluorite,
	_DivisionName[18:24]: DivisionQuartz,
	_DivisionName[24:30]: DivisionPyrite,
	_DivisionName[30:36]: DivisionGarnet,
	_DivisionName[36:44]: DivisionCorundum,
	_DivisionName[44:51]: DivisionDiamond,
	_DivisionName[51:58]: DivisionBismuth,
}

// ParseDivision attempts to convert a string to a Division.
func ParseDivision(name string) (Division, error) {
	if x, ok := _DivisionValue[name]; ok {
		return x, nil
	}
	return Division(0), fmt.Errorf("%s is %w", name, ErrInvalidDivision)
}

// MarshalText implements the text marshaller method.
func (x Division) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Division) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseDivision(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *Division) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

var errDivisionNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *Division) Scan(value interface{}) (err error) {
	if value == nil {
		*x = Division(0)
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case int64:
		*x = Division(v)
	case string:
		*x, err = ParseDivision(v)
	case []byte:
		*x, err = ParseDivision(string(v))
	case Division:
		*x = v
	case int:
		*x = Division(v)
	case *Division:
		if v == nil {
			return errDivisionNilPtr
		}
		*x = *v
	case uint:
		*x = Division(v)
	case uint64:
		*x = Division(v)
	case *int:
		if v == nil {
			return errDivisionNilPtr
		}
		*x = Division(*v)
	case *int64:
		if v == nil {
			return errDivisionNilPtr
		}
		*x = Division(*v)
	case float64: // json marshals everything as a float64 if it's a number
		*x = Division(v)
	case *float64: // json marshals everything as a float64 if it's a number
		if v == nil {
			return errDivisionNilPtr
		}
		*x = Division(*v)
	case *uint:
		if v == nil {
			return errDivisionNilPtr
		}
		*x = Division(*v)
	case *uint64:
		if v == nil {
			return errDivisionNilPtr
		}
		*x = Division(*v)
	case *string:
		if v == nil {
			return errDivisionNilPtr
		}
		*x, err = ParseDivision(*v)
	}

	return
}

// Value implements the driver Valuer interface.
func (x Division) Value() (driver.Value, error) {
	return x.String(), nil
}
