// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package enum

import (
	"database/sql/driver"
	"errors"
	"fmt"
)

const (
	// DivisionBeginnerOne is a Division of type BeginnerOne.
	DivisionBeginnerOne Division = iota
	// DivisionBeginnerTwo is a Division of type BeginnerTwo.
	DivisionBeginnerTwo
	// DivisionBeginnerThree is a Division of type BeginnerThree.
	DivisionBeginnerThree
	// DivisionAdvancedOne is a Division of type AdvancedOne.
	DivisionAdvancedOne
	// DivisionAdvancedTwo is a Division of type AdvancedTwo.
	DivisionAdvancedTwo
	// DivisionAdvancedThree is a Division of type AdvancedThree.
	DivisionAdvancedThree
	// DivisionProfessionalOne is a Division of type ProfessionalOne.
	DivisionProfessionalOne
	// DivisionProfessionalTwo is a Division of type ProfessionalTwo.
	DivisionProfessionalTwo
	// DivisionProfessionalThree is a Division of type ProfessionalThree.
	DivisionProfessionalThree
)

var ErrInvalidDivision = errors.New("not a valid Division")

const _DivisionName = "beginnerOnebeginnerTwobeginnerThreeadvancedOneadvancedTwoadvancedThreeprofessionalOneprofessionalTwoprofessionalThree"

var _DivisionMap = map[Division]string{
	DivisionBeginnerOne:       _DivisionName[0:11],
	DivisionBeginnerTwo:       _DivisionName[11:22],
	DivisionBeginnerThree:     _DivisionName[22:35],
	DivisionAdvancedOne:       _DivisionName[35:46],
	DivisionAdvancedTwo:       _DivisionName[46:57],
	DivisionAdvancedThree:     _DivisionName[57:70],
	DivisionProfessionalOne:   _DivisionName[70:85],
	DivisionProfessionalTwo:   _DivisionName[85:100],
	DivisionProfessionalThree: _DivisionName[100:117],
}

// String implements the Stringer interface.
func (x Division) String() string {
	if str, ok := _DivisionMap[x]; ok {
		return str
	}
	return fmt.Sprintf("Division(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Division) IsValid() bool {
	_, ok := _DivisionMap[x]
	return ok
}

var _DivisionValue = map[string]Division{
	_DivisionName[0:11]:    DivisionBeginnerOne,
	_DivisionName[11:22]:   DivisionBeginnerTwo,
	_DivisionName[22:35]:   DivisionBeginnerThree,
	_DivisionName[35:46]:   DivisionAdvancedOne,
	_DivisionName[46:57]:   DivisionAdvancedTwo,
	_DivisionName[57:70]:   DivisionAdvancedThree,
	_DivisionName[70:85]:   DivisionProfessionalOne,
	_DivisionName[85:100]:  DivisionProfessionalTwo,
	_DivisionName[100:117]: DivisionProfessionalThree,
}

// ParseDivision attempts to convert a string to a Division.
func ParseDivision(name string) (Division, error) {
	if x, ok := _DivisionValue[name]; ok {
		return x, nil
	}
	return Division(0), fmt.Errorf("%s is %w", name, ErrInvalidDivision)
}

// MarshalText implements the text marshaller method.
func (x Division) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Division) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseDivision(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *Division) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

var errDivisionNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *Division) Scan(value interface{}) (err error) {
	if value == nil {
		*x = Division(0)
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case int64:
		*x = Division(v)
	case string:
		*x, err = ParseDivision(v)
	case []byte:
		*x, err = ParseDivision(string(v))
	case Division:
		*x = v
	case int:
		*x = Division(v)
	case *Division:
		if v == nil {
			return errDivisionNilPtr
		}
		*x = *v
	case uint:
		*x = Division(v)
	case uint64:
		*x = Division(v)
	case *int:
		if v == nil {
			return errDivisionNilPtr
		}
		*x = Division(*v)
	case *int64:
		if v == nil {
			return errDivisionNilPtr
		}
		*x = Division(*v)
	case float64: // json marshals everything as a float64 if it's a number
		*x = Division(v)
	case *float64: // json marshals everything as a float64 if it's a number
		if v == nil {
			return errDivisionNilPtr
		}
		*x = Division(*v)
	case *uint:
		if v == nil {
			return errDivisionNilPtr
		}
		*x = Division(*v)
	case *uint64:
		if v == nil {
			return errDivisionNilPtr
		}
		*x = Division(*v)
	case *string:
		if v == nil {
			return errDivisionNilPtr
		}
		*x, err = ParseDivision(*v)
	}

	return
}

// Value implements the driver Valuer interface.
func (x Division) Value() (driver.Value, error) {
	return x.String(), nil
}
